### ISSUE TITLE
[Celeste][Epic] Some services are not working

### ISSUE THREAD

**Issue by kamikazebr** [1Hive/gardens-ui#821]
it close https://github.com/1Hive/gardens/issues/508

### Celeste related services
- [x] Fixed the subscribe email in the notification service (1) 
- [x] Fixed some services to rinkeby and polygon network - more specific the Ingress
- [x] Update the subgraph https://github.com/1Hive/celeste-subgraph , Rinkeby is not loading the dashboard
- [x] Investigate why has accumulated numbers of transactions goes altho of heartbeat() function (2)
- [x] Find the contract address Court and check if it's correct in the Pods
- [x] 1Hive/celeste-dashboard#154
- [x] 1Hive/celeste-backend#16
- [x] Need refill some ETH (Rinkeby, xdai) and Matic (Polygon on the wallet to run hearbeat
- [x] Configure monitoring health notifications of services. - Grafana its working to check about errors.
- [x] Configure monitoring balance of wallets - https://github.com/1Hive/notify_low_balance

### Other services
- [x] 1Hive/honeymaker#11

~**¹** Need test the route /dispute/number across network if it work as expect.~
~**²** Contracts was reseted. But in Rinkeby the terms have 4 min of duration, so probably ran out money in the account to keep it updated because fee~

**Comment by kamikazebr** [comment]
![image](https://user-images.githubusercontent.com/691510/154096391-87a657ce-9501-4481-87d9-ee3963353927.png)
I found more errors happening - Digging on https://github.com/1Hive/celeste-backend/issues/16 too about it
